- name: play1
  hosts: all 
  tasks:
    - name: Task1 of play1 
      ansible.builtin.debug:
        msg: "Hai from task1 of play1"

    - name: Task2 of play1 
      ansible.builtin.debug:
        msg: "Ola from task2 of play1"

- name: play2
  hosts: frontend 
  tasks:
    - name: Task1 of play1 
      ansible.builtin.debug:
        msg: "Olympics"

    - name: Task2 of play2 
      ansible.builtin.debug:
        msg: "2024 - France"